'use strict';
(() => {
const C=BlobbyCore,T=BlobbyThemes,B=BlobbyBridge,L=BlobbyLayout,$=id=>document.getElementById(id),root=document.documentElement,shell=$('appShell');
function read(key,fallback){try{const v=localStorage.getItem(key);return v===null?fallback:JSON.parse(v);}catch{return fallback;}}
let state=C.migrate(read),p=state.prefs,storageOK=true,editingShortcut=-1,layoutSnapshot=null,pendingOrder=null,importMode='theme',activeSettings='appearance';
const effects=new BlobbyEffects.EffectsEngine($('effectsCanvas'));
function save(){state.prefs=p;try{localStorage.setItem(C.STORAGE_KEY,C.serialize(state));storageOK=true;$('saveStatus').textContent='Saved automatically on this device';}catch{storageOK=false;$('saveStatus').textContent='Storage unavailable — changes last for this session';}}
function el(tag,cls='',text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;}
function btn(text,fn,cls=''){const b=el('button',cls,text);b.type='button';if(fn)b.addEventListener('click',fn);return b;}
function say(text){$('status').textContent=text||'';}
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},0);}
function ask(title,detail,{value='',accept='Save',input=true}={}){return new Promise(resolve=>{const d=$('promptDialog');$('promptTitle').textContent=title;$('promptDetail').textContent=detail||'';$('promptLabel').hidden=!input;$('promptInput').value=value;$('promptInput').required=input;$('promptAccept').textContent=accept;let result=null;const done=()=>{d.removeEventListener('close',done);resolve(result);};d.addEventListener('close',done);$('promptForm').onsubmit=e=>{e.preventDefault();result=input?$('promptInput').value.trim():true;if(input&&!result)return;d.close();};$('promptCancel').onclick=()=>d.close();d.showModal();setTimeout(()=>input?$('promptInput').focus():$('promptAccept').focus(),20);});}
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).close()));
function currentTab(){let t=state.tabs.find(x=>x.id===state.activeTab);if(!t){t=state.tabs[0];state.activeTab=t.id;}return t;}
function currentTheme(){return T.getTheme(p.theme,state.customThemes);}
function appMode(){return B.isAppInventor();}
function expandUI(reason='panel'){B.send('EXPAND_UI',reason);}
function restoreUI(reason='panel'){B.send('RESTORE_UI',currentTab().url?'browser':'home');}
function syncBridgeBadge(){$('bridgeBadge').textContent=appMode()?'App Inventor connected':'Desktop demo';$('bridgeBadge').classList.toggle('connected',appMode());}
function applyBackground(){const mode=p.backgroundMode;let bg=p.backgroundGradient;if(mode==='solid')bg=p.backgroundSolid;if(mode==='image'&&p.backgroundImage)bg=`url("${String(p.backgroundImage).replace(/"/g,'%22')}")`;
 root.style.setProperty('--custom-background',bg||p.backgroundGradient);root.style.setProperty('--bg-brightness',p.backgroundBrightness/100);root.style.setProperty('--bg-blur',`${p.backgroundBlur}px`);root.style.setProperty('--bg-opacity',p.backgroundOpacity/100);root.style.setProperty('--bg-overlay',p.backgroundOverlay/100);root.style.setProperty('--bg-size',p.backgroundSize);root.style.setProperty('--bg-position',p.backgroundPosition);root.dataset.backgroundMode=mode;}
function apply(){const theme=currentTheme();T.apply(theme,p,root);applyBackground();root.dataset.rainGlass=String(!!p.rainGlass&&!p.performance);$('performanceBadge').hidden=!p.performance;$('layoutEditButton').disabled=!!p.layoutLocked;$('layoutEditButton').title=p.layoutLocked?'Unlock layout in Settings to edit':'Edit layout';$('subtitleText').hidden=!p.showSubtitle;L.apply(p,shell);effects.configure(p,theme);syncBridgeBadge();syncNavigation();renderTabs();if(appMode()||!currentTab().url||!p.showPreview||(p.layoutHidden||[]).includes('preview'))hidePreview();else showPreview(currentTab().url);renderShortcuts();renderRecent();syncSettings();save();}
function renderTabs(){const list=$('tabList');list.replaceChildren();for(const tab of state.tabs){const wrap=el('div','browser-tab');wrap.setAttribute('role','tab');wrap.setAttribute('aria-selected',String(tab.id===state.activeTab));wrap.dataset.tabId=tab.id;const fav=el('span','tab-favicon',tab.favicon||'●'),main=btn(tab.title||'New tab',()=>switchTab(tab.id),'tab-main'),close=btn('×',e=>closeTab(tab.id,e),'tab-close');main.title=tab.url||'New tab';wrap.append(fav,main,close);list.append(wrap);} $('newTabButton').disabled=state.tabs.length>=p.maxTabs;}
function newTab(){if(state.tabs.length>=p.maxTabs){say(`Tab limit reached (${p.maxTabs}).`);return;}const t=C.createTab();state.tabs.push(t);state.activeTab=t.id;save();renderTabs();syncNavigation();B.send('NEW_TAB',t.id);B.send('SHOW_HOME',t.id);hidePreview();focusHomeSearch();}
function closeTab(id,event){if(event&&event.stopPropagation)event.stopPropagation();if(state.tabs.length===1){const t=state.tabs[0];Object.assign(t,C.createTab(),{id:t.id});state.activeTab=t.id;B.send('CLOSE_TAB',id);B.send('SHOW_HOME',t.id);hidePreview();apply();return;}const idx=state.tabs.findIndex(t=>t.id===id);if(idx<0)return;state.tabs.splice(idx,1);B.send('CLOSE_TAB',id);if(state.activeTab===id){const t=state.tabs[Math.max(0,idx-1)]||state.tabs[0];state.activeTab=t.id;B.send('SWITCH_TAB',t.id);if(t.url)B.send('NAVIGATE',t.url);else B.send('SHOW_HOME',t.id);}save();renderTabs();syncNavigation();}
function switchTab(id){const t=state.tabs.find(x=>x.id===id);if(!t)return;state.activeTab=id;B.send('SWITCH_TAB',id);if(t.url){$('addressBar').value=t.url;if(appMode()){B.send('NAVIGATE',t.url);hidePreview();}else showPreview(t.url);}else{B.send('SHOW_HOME',id);$('addressBar').value='';hidePreview();}save();renderTabs();syncNavigation();}
function navigate(raw){const url=C.resolve(raw,p.engine,p.customSearchPrefix);if(!url){say('Enter a website or search term.');return;}const t=currentTab();C.navigateTab(t,url,true);if(p.rememberRecent)state.recent=C.recordRecent(state.recent,url,t.title);save();renderTabs();renderRecent();syncNavigation();$('addressBar').value=url;B.send('NAVIGATE',url);if(appMode())hidePreview();else showPreview(url);say(appMode()?`Opening ${C.titleFromUrl(url)} in the browser WebViewer.`:`Demo: ${C.titleFromUrl(url)} would open in the App Inventor browser WebViewer.`);}
function goHome(){const t=currentTab();t.url='';t.title='New tab';t.history=[];t.historyIndex=-1;save();renderTabs();syncNavigation();hidePreview();B.send('HOME');B.send('SHOW_HOME',t.id);focusHomeSearch();}
function back(){const t=currentTab();const url=C.goHistory(t,-1);if(!url)return;save();renderTabs();syncNavigation();B.send('BACK',url);if(!appMode())showPreview(url);}
function forward(){const t=currentTab();const url=C.goHistory(t,1);if(!url)return;save();renderTabs();syncNavigation();B.send('FORWARD',url);if(!appMode())showPreview(url);}
function refresh(){const t=currentTab();if(!t.url)return;B.send('REFRESH');if(!appMode())showPreview(t.url);}
function syncNavigation(){const t=currentTab();$('backButton').disabled=!C.canBack(t);$('forwardButton').disabled=!C.canForward(t);$('refreshButton').disabled=!t.url;if(document.activeElement!==$('addressBar'))$('addressBar').value=t.url||'';$('clearAddressButton').hidden=!$('addressBar').value;}
function showPreview(url){if(!p.showPreview||(p.layoutHidden||[]).includes('preview'))return;const block=$('previewBlock');block.hidden=false;$('previewTitle').textContent=C.titleFromUrl(url);$('previewUrl').textContent=url;block.dataset.previewUrl=url;}
function hidePreview(){$('previewBlock').hidden=true;$('previewBlock').dataset.previewUrl='';}
function openExternal(){const url=currentTab().url||$('previewBlock').dataset.previewUrl;if(!url)return;if(appMode())B.send('OPEN_EXTERNAL',url);else window.open(url,'_blank','noopener,noreferrer');}
$('addressForm').addEventListener('submit',e=>{e.preventDefault();navigate($('addressBar').value);});$('homeSearchForm').addEventListener('submit',e=>{e.preventDefault();navigate($('homeSearchInput').value);});
$('backButton').onclick=back;$('forwardButton').onclick=forward;$('refreshButton').onclick=refresh;$('homeButton').onclick=goHome;$('externalButton').onclick=openExternal;$('previewExternal').onclick=openExternal;$('newTabButton').onclick=newTab;$('miniHome').onclick=e=>{e.preventDefault();goHome();};$('clearAddressButton').onclick=()=>{$('addressBar').value='';$('addressBar').focus();syncNavigation();};$('addressBar').addEventListener('input',()=>{$('clearAddressButton').hidden=!$('addressBar').value;});
window.addEventListener('blobby:appmessage',e=>{const {command,payload}=e.detail,t=currentTab();if(command==='URL'){const u=C.safeUrl(payload);if(u){if(t.history[t.historyIndex]!==u)C.navigateTab(t,u,true);else t.url=u;$('addressBar').value=u;save();renderTabs();syncNavigation();}}
 else if(command==='TITLE'){t.title=payload.slice(0,80)||C.titleFromUrl(t.url);save();renderTabs();}
 else if(command==='HOME_SHOWN'){hidePreview();}
 else if(command==='CONNECTED')syncBridgeBadge();});
window.addEventListener('blobby:demo-command',()=>syncBridgeBadge());

function iconFor(link){return (link.icon||link.label.slice(0,1)||'?').slice(0,4);}
function renderShortcuts(){const grid=$('shortcutGrid');grid.replaceChildren();const groups=new Map();for(const link of state.links){const f=link.folder||'';if(!groups.has(f))groups.set(f,[]);groups.get(f).push(link);}for(const [folder,links] of groups){if(folder){const h=el('div','shortcut-folder',folder);grid.append(h);}for(const link of links){const a=btn('',()=>navigate(link.url),'shortcut-tile');const icon=el('span','shortcut-icon',iconFor(link)),name=el('span','shortcut-name',link.label);a.append(icon,name);a.title=link.url;grid.append(a);}}if(!state.links.length)grid.append(el('p','empty-state','No shortcuts yet. Add one in Settings → Shortcuts.'));}
function renderRecent(){const box=$('recentList');box.replaceChildren();if(!state.recent.length){box.append(el('p','empty-state','Pages you open from blobby.vip will appear here.'));return;}for(const item of state.recent.slice(0,p.performance?5:10)){const row=el('div','recent-row'),text=btn('',()=>navigate(item.url),'recent-main');text.append(el('strong','',item.label),el('small','',item.url));const time=el('time','',new Date(item.time).toLocaleDateString(undefined,{month:'short',day:'numeric'}));row.append(text,time);box.append(row);}}
$('clearRecentButton').onclick=async()=>{const ok=await ask('Clear recent pages?','This removes the recent-page list saved by blobby.vip.',{accept:'Clear',input:false});if(ok){state.recent=[];renderRecent();save();}};
function openShortcut(index=-1){editingShortcut=index;const x=index>=0?state.links[index]:{label:'',url:'',folder:'',icon:''};$('shortcutTitle').textContent=index>=0?'Edit shortcut':'Add shortcut';$('shortcutName').value=x.label;$('shortcutUrl').value=x.url;$('shortcutFolder').value=x.folder||'';$('shortcutIcon').value=x.icon||'';$('shortcutIndex').value=String(index);$('deleteShortcutButton').hidden=index<0;$('shortcutError').textContent='';$('shortcutDialog').showModal();setTimeout(()=>$('shortcutName').focus(),20);}
$('manageShortcutsButton').onclick=()=>{openSettings('shortcuts');};
$('shortcutForm').onsubmit=e=>{e.preventDefault();const label=$('shortcutName').value.trim(),url=C.resolve($('shortcutUrl').value,p.engine,p.customSearchPrefix),folder=$('shortcutFolder').value.trim(),icon=$('shortcutIcon').value.trim()||label.slice(0,1).toUpperCase();if(!label||!url){$('shortcutError').textContent='Enter a valid name and website.';return;}const item={label,url,folder,icon};if(editingShortcut>=0)state.links[editingShortcut]=item;else state.links.push(item);$('shortcutDialog').close();renderShortcuts();renderShortcutSettings();save();};
$('deleteShortcutButton').onclick=async()=>{if(editingShortcut<0)return;const ok=await ask('Delete shortcut?','This removes it from Quick access.',{accept:'Delete',input:false});if(ok){state.links.splice(editingShortcut,1);$('shortcutDialog').close();renderShortcuts();renderShortcutSettings();save();}};
function moveShortcut(index,delta){const j=index+delta;if(j<0||j>=state.links.length)return;const [x]=state.links.splice(index,1);state.links.splice(j,0,x);renderShortcuts();renderShortcutSettings();save();}

const categories=[['appearance','Appearance'],['themes','Themes'],['layout','Layout'],['ambient','Ambient Effects'],['browser','Browser'],['tabs','Tabs'],['homepage','Homepage'],['shortcuts','Shortcuts'],['performance','Performance'],['advanced','Advanced']];
function makeSettings(){const nav=$('settingsNav'),panels=$('settingsPanels');nav.replaceChildren();panels.replaceChildren();for(const [id,name] of categories){const n=btn(name,()=>showSettings(id),'settings-nav-button');n.dataset.category=id;nav.append(n);const panel=el('section','settings-panel');panel.id='settings-'+id;panel.dataset.category=id;panel.append(el('h3','settings-title',name));panels.append(panel);}buildAppearance();buildThemes();buildLayout();buildAmbient();buildBrowser();buildTabs();buildHomepage();buildShortcuts();buildPerformance();buildAdvanced();showSettings(activeSettings);}
function panel(id){return $('settings-'+id);}function group(parent,title,description=''){const g=el('div','setting-group');g.dataset.settingSearch=(title+' '+description).toLowerCase();g.append(el('h4','',title));if(description)g.append(el('p','setting-help',description));parent.append(g);return g;}
function row(parent,label,description=''){const r=el('div','setting-row');r.dataset.settingSearch=(label+' '+description).toLowerCase();const copy=el('div','setting-copy');copy.append(el('strong','',label));if(description)copy.append(el('small','',description));r.append(copy);parent.append(r);return r;}
function toggle(parent,key,label,description='',scope=p){const r=row(parent,label,description),i=el('input','switch-input');i.type='checkbox';i.checked=!!scope[key];i.addEventListener('change',()=>{scope[key]=i.checked;changed();});r.append(i);return i;}
function range(parent,key,label,min,max,step=1,unit='',scope=p){const r=row(parent,label,''),wrap=el('div','range-control'),i=el('input');i.type='range';i.min=min;i.max=max;i.step=step;i.value=scope[key];const out=el('output','',`${scope[key]}${unit}`);i.addEventListener('input',()=>{scope[key]=Number(i.value);out.textContent=`${i.value}${unit}`;changed(false);});i.addEventListener('change',()=>changed());wrap.append(i,out);r.append(wrap);return i;}
function select(parent,key,label,options,scope=p){const r=row(parent,label,''),s=el('select');for(const [v,n] of options){const o=el('option','',n);o.value=v;s.append(o);}s.value=scope[key];s.addEventListener('change',()=>{scope[key]=s.value;changed();});r.append(s);return s;}
function color(parent,key,label,scope,onChange){const r=row(parent,label,''),wrap=el('div','color-control'),c=el('input'),text=el('input');c.type='color';c.value=scope[key];text.value=scope[key];text.maxLength=7;const apply=v=>{if(!/^#[0-9a-f]{6}$/i.test(v))return;scope[key]=v.toLowerCase();c.value=scope[key];text.value=scope[key];if(onChange)onChange();else changed();};c.oninput=()=>apply(c.value);text.onchange=()=>apply(text.value);wrap.append(c,text);r.append(wrap);return c;}
function actionRow(parent,...buttons){const r=el('div','settings-actions');for(const b of buttons)r.append(b);parent.append(r);return r;}
function buildAppearance(){const x=panel('appearance');const g=group(x,'Surface & motion','Tune the shape, transparency, blur, shadows, and interaction feel.');toggle(g,'glass','Glass panels','Adds translucent panels and background blur.');range(g,'panelOpacity','Panel opacity',.35,1,.05,'');range(g,'blur','Glass blur',0,36,1,'px');range(g,'shadow','Shadow strength',0,60,1,'%');range(g,'radius','Corner radius',4,32,1,'px');toggle(g,'hoverEffects','Hover effects','Small lifts and highlights on pointer devices.');toggle(g,'animations','Animations','Master animation switch.');range(g,'animationSpeed','Animation speed',.4,2,.1,'×');toggle(g,'reducedMotion','Reduced motion','Disables motion-heavy effects regardless of other choices.');
 const b=group(x,'Background','Use a solid color, gradient, or your own image.');select(b,'backgroundMode','Background type',[['gradient','Gradient'],['solid','Solid color'],['image','Image']]);color(b,'backgroundSolid','Solid color',p);const rr=row(b,'Gradient CSS','Example: linear-gradient(135deg,#090b13,#24123e)'),inp=el('input');inp.value=p.backgroundGradient;inp.addEventListener('change',()=>{p.backgroundGradient=inp.value.trim()||p.backgroundGradient;changed();});rr.append(inp);const ur=row(b,'Image URL','Use a direct image URL or upload an image below.'),ui=el('input');ui.placeholder='https://...';ui.value=p.backgroundImage&&!p.backgroundImage.startsWith('data:')?p.backgroundImage:'';ui.addEventListener('change',()=>{p.backgroundImage=ui.value.trim();p.backgroundMode='image';changed();});ur.append(ui);actionRow(b,btn('Upload image',()=>$('backgroundUpload').click()),btn('Clear image',()=>{p.backgroundImage='';changed();},'text-button'));range(b,'backgroundBrightness','Brightness',30,150,5,'%');range(b,'backgroundBlur','Background blur',0,24,1,'px');range(b,'backgroundOpacity','Background opacity',20,100,5,'%');range(b,'backgroundOverlay','Dark overlay',0,80,5,'%');select(b,'backgroundSize','Image scaling',[['cover','Cover'],['contain','Contain'],['auto','Original']]);select(b,'backgroundPosition','Image position',[['center','Center'],['top','Top'],['bottom','Bottom'],['left','Left'],['right','Right']]);}
function ensureEditableTheme(){let c=state.customThemes.find(t=>t.id===p.theme);if(c)return c;const base=currentTheme();c={id:C.uid('theme'),name:'Custom theme',colors:Object.fromEntries(T.keys.map(k=>[k,base[k]]))};state.customThemes.push(c);p.theme=c.id;return c;}
function themePreviewCard(id,theme,name){const card=btn('',()=>{p.theme=id;changed();renderThemeSettings();},'theme-card');card.dataset.themeId=id;card.setAttribute('aria-pressed',String(p.theme===id));const sw=el('span','theme-swatches');for(const k of ['bg','panel','accent','accent2']){const i=el('i');i.style.background=theme[k];sw.append(i);}card.append(sw,el('strong','',name));return card;}
function buildThemes(){renderThemeSettings();}
function renderThemeSettings(){const x=panel('themes');if(!x)return;x.replaceChildren(el('h3','settings-title','Themes'));const pre=group(x,'Preset themes','Choose a base and customize every color below.'),grid=el('div','theme-grid');for(const [id,t] of Object.entries(T.presets))grid.append(themePreviewCard(id,t,t.name));pre.append(grid);
 const base=currentTheme(),draft=Object.fromEntries(T.keys.map(k=>[k,base[k]])),ed=group(x,'Custom theme editor','Changing a color creates or updates an editable custom copy.');for(const k of T.keys){const labels={bg:'Background',bg2:'Secondary background',panel:'Panel',panel2:'Secondary panel',text:'Text',muted:'Muted text',accent:'Primary accent',accent2:'Secondary accent',line:'Border',glow:'Glow'};color(ed,k,labels[k],draft,()=>{let cur=state.customThemes.find(t=>t.id===p.theme);if(!cur){cur={id:C.uid('theme'),name:'Custom theme',colors:C.clone(draft)};state.customThemes.push(cur);p.theme=cur.id;}else cur.colors=C.clone(draft);changed();});}
 const actions=group(x,'Custom themes','Save variants, rename them, duplicate them, or move them between devices.');actionRow(actions,btn('Save as…',saveThemeAs,'primary-button'),btn('Rename',renameTheme),btn('Duplicate',duplicateTheme));actionRow(actions,btn('Export theme',exportTheme),btn('Import theme',()=>{importMode='theme';$('importInput').click();}),btn('Delete',deleteTheme,'danger-button'));const list=el('div','saved-list');for(const t of state.customThemes){const r=el('div','saved-item');r.append(btn(t.name,()=>{p.theme=t.id;changed();renderThemeSettings();},'saved-main'),btn('Duplicate',()=>duplicateTheme(t.id),'text-button'));list.append(r);}actions.append(list);syncSettingsSearch();}
async function saveThemeAs(){const name=await ask('Save custom theme','Give this colorway a name.',{value:'My theme'});if(!name)return;const base=currentTheme(),t={id:C.uid('theme'),name,colors:Object.fromEntries(T.keys.map(k=>[k,base[k]]))};state.customThemes.push(t);p.theme=t.id;changed();renderThemeSettings();}
async function renameTheme(){const t=state.customThemes.find(x=>x.id===p.theme);if(!t){say('Preset themes cannot be renamed. Save it as a custom theme first.');return;}const name=await ask('Rename theme','Choose a new name.',{value:t.name});if(name){t.name=name;save();renderThemeSettings();}}
function duplicateTheme(id=p.theme){const base=id?T.getTheme(id,state.customThemes):currentTheme();const source=state.customThemes.find(x=>x.id===id);const t={id:C.uid('theme'),name:(source?.name||base.name||'Theme')+' Copy',colors:Object.fromEntries(T.keys.map(k=>[k,base[k]]))};state.customThemes.push(t);p.theme=t.id;changed();renderThemeSettings();}
async function deleteTheme(){const idx=state.customThemes.findIndex(x=>x.id===p.theme);if(idx<0){say('Preset themes cannot be deleted.');return;}const ok=await ask('Delete custom theme?','This cannot be undone.',{accept:'Delete',input:false});if(ok){state.customThemes.splice(idx,1);p.theme='midnight';changed();renderThemeSettings();}}
function exportTheme(){const t=currentTheme();download('blobby-theme.json',JSON.stringify({type:'blobby-theme',name:t.name||'Custom',colors:Object.fromEntries(T.keys.map(k=>[k,t[k]]))},null,2));}
function buildLayout(){const x=panel('layout'),g=group(x,'Layout presets','Start with a preset, then drag blocks into your own order.'),grid=el('div','layout-grid');for(const [id,v] of Object.entries(C.layoutPresets)){const b=btn(v.name,()=>{L.usePreset(p,id);changed();},'layout-card');b.dataset.layout=id;grid.append(b);}g.append(grid);toggle(g,'layoutLocked','Lock layout','Prevents accidental rearranging outside explicit edit mode.');actionRow(g,btn('Edit layout',startLayoutEdit,'primary-button'),btn('Reset layout',()=>{L.usePreset(p,'classic');changed();}));const vis=group(x,'Visible blocks','Hide homepage sections without deleting their data.');toggle(vis,'showSubtitle','Show subtitle');toggle(vis,'showClock','Show clock');toggle(vis,'showShortcuts','Show shortcuts');toggle(vis,'showRecent','Show recent pages');toggle(vis,'showPreview','Show desktop preview');const saved=group(x,'Saved layouts','Save and restore your own block arrangements.');actionRow(saved,btn('Save current layout',saveCurrentLayout,'primary-button'));renderSavedLayouts(saved);}
async function saveCurrentLayout(){const name=await ask('Save layout','Name this arrangement.',{value:'My layout'});if(!name)return;state.savedLayouts.push({id:C.uid('layout'),name,order:C.clone(p.layoutOrder),hidden:C.clone(p.layoutHidden),preset:p.layoutPreset});save();makeSettings();showSettings('layout');}
function renderSavedLayouts(parent){for(const s of state.savedLayouts){const r=el('div','saved-item');r.append(btn(s.name,()=>{p.layoutOrder=C.clone(s.order);p.layoutHidden=C.clone(s.hidden||[]);p.layoutPreset=s.preset||'classic';changed();},'saved-main'),btn('Delete',()=>{state.savedLayouts=state.savedLayouts.filter(x=>x.id!==s.id);save();makeSettings();showSettings('layout');},'text-button'));parent.append(r);}}
function buildAmbient(){const x=panel('ambient'),master=group(x,'Ambient engine','Multiple lightweight effects can run together. Performance mode disables the canvas-heavy ones.');toggle(master,'effectsMaster','Enable ambient effects');range(master,'effectDensity','Density',10,100,5,'%');range(master,'effectSpeed','Speed',.3,2.5,.1,'×');range(master,'effectOpacity','Opacity',.1,1,.05,'');range(master,'effectSize','Particle size',.5,2.5,.1,'×');const fx=group(x,'Effects','Mix compatible effects.');const names={snow:'Snow',rain:'Rain',stars:'Stars',particles:'Particles',fireflies:'Fireflies',orbs:'Floating orbs',aurora:'Aurora',fog:'Fog',matrix:'Matrix rain',bubbles:'Bubbles',shooting:'Shooting stars',waves:'Gradient waves',rgbGlow:'RGB glow',dust:'Soft dust'};for(const [k,n] of Object.entries(names))toggle(fx,k,n,'',p.effects);const rain=group(x,'Rain mode','Extra rain-specific ambience.');toggle(rain,'rainLightning','Occasional lightning flashes');toggle(rain,'rainGlass','Rainy glass overlay');const rgb=group(x,'RGB mode','Animate selected accents without forcing the whole interface into rainbow colors.');toggle(rgb,'rgb','Enable RGB mode');range(rgb,'rgbSpeed','RGB cycle speed',2,30,1,'s');range(rgb,'rgbIntensity','RGB intensity',0,100,5,'%');range(rgb,'rgbSaturation','RGB saturation',20,140,5,'%');for(const [k,n] of Object.entries({logo:'Logo',tabs:'Active tab',address:'Address bar',buttons:'Buttons',ambient:'Ambient glow'}))toggle(rgb,k,`RGB ${n}`,'',p.rgbAreas);}
function buildBrowser(){const x=panel('browser'),g=group(x,'Search & navigation','The GitHub page controls the second MIT App Inventor WebViewer instead of embedding sites in an iframe.');select(g,'engine','Search engine',[["google","Google"],["duck","DuckDuckGo"],["bing","Bing"],["custom","Custom"]]);const r=row(g,'Custom search URL','Use a URL prefix such as https://example.com/search?q= or a template containing %s.'),i=el('input');i.value=p.customSearchPrefix;i.placeholder='https://example.com/search?q=';i.onchange=()=>{p.customSearchPrefix=i.value.trim();changed();};r.append(i);toggle(g,'rememberRecent','Remember recent pages');toggle(g,'autofocus','Autofocus search on desktop');const info=group(x,'App Inventor bridge','Current bridge status and command behavior.');const badge=el('div','bridge-card');badge.innerHTML=`<strong>${appMode()?'Connected':'Desktop demo mode'}</strong><span>${appMode()?'Commands are being sent to window.AppInventor.setWebViewString().':'Navigation requests show a preview card and can open externally.'}</span>`;info.append(badge);}
function buildTabs(){const x=panel('tabs'),g=group(x,'Tab behavior','Tabs keep their own URL history and can be restored from local storage.');range(g,'maxTabs','Maximum tabs',2,20,1,'');toggle(g,'tabAnimations','Animate tab changes');const info=row(g,'Open tabs',`${state.tabs.length} currently open`);info.append(btn('Close other tabs',()=>{const keep=currentTab();state.tabs=[keep];state.activeTab=keep.id;changed();B.send('CLOSE_OTHER_TABS',keep.id);},'text-button'));}
function buildHomepage(){const x=panel('homepage'),g=group(x,'Homepage','Choose which new-tab widgets appear. You can rearrange them in Layout edit mode.');toggle(g,'showSubtitle','Show “made by panga”');toggle(g,'showClock','Show clock');toggle(g,'showShortcuts','Show shortcuts');toggle(g,'showRecent','Show recent pages');toggle(g,'showPreview','Show desktop preview');}
function buildShortcuts(){renderShortcutSettings();}
function renderShortcutSettings(){const x=panel('shortcuts');if(!x)return;x.replaceChildren(el('h3','settings-title','Shortcuts'));const g=group(x,'Quick access','Add, edit, group, and rearrange shortcuts.');actionRow(g,btn('Add shortcut',()=>openShortcut(-1),'primary-button'));const list=el('div','shortcut-settings-list');state.links.forEach((link,index)=>{const r=el('div','saved-item shortcut-setting');r.append(el('span','shortcut-mini-icon',iconFor(link)));const copy=el('div','saved-main');copy.append(el('strong','',link.label),el('small','',link.folder?`${link.folder} · ${link.url}`:link.url));r.append(copy,btn('↑',()=>moveShortcut(index,-1),'text-button'),btn('↓',()=>moveShortcut(index,1),'text-button'),btn('Edit',()=>openShortcut(index),'text-button'));list.append(r);});g.append(list);syncSettingsSearch();}
function buildPerformance(){const x=panel('performance'),g=group(x,'Performance mode','Reduces GPU and JavaScript work while keeping the browser controls usable.');toggle(g,'performance','Enable performance mode','Stops canvas particles, blur, RGB animation, expensive shadows, and extra motion.');const n=el('div','performance-note');n.innerHTML='<strong>What it changes</strong><span>Ambient particles stop, blur is removed, shadows are simplified, hidden effects remain saved, and recent rendering is shortened.</span>';g.append(n);}
function buildAdvanced(){const x=panel('advanced'),profiles=group(x,'Customization profiles','Save the complete appearance, layout, effects, homepage, and browser preferences as a profile.');actionRow(profiles,btn('Save profile',saveProfile,'primary-button'));for(const pr of state.profiles){const r=el('div','saved-item');r.append(btn(pr.name,()=>{p=C.sanitizePrefs(C.clone(pr.prefs));state.prefs=p;changed();makeSettings();showSettings('advanced');},'saved-main'),btn('Delete',()=>{state.profiles=state.profiles.filter(x=>x.id!==pr.id);save();makeSettings();showSettings('advanced');},'text-button'));profiles.append(r);}const data=group(x,'Import & export','Move all blobby.vip settings between browsers.');actionRow(data,btn('Export settings',()=>download('blobby-settings.json',JSON.stringify({type:'blobby-settings',version:C.VERSION,state},null,2)),'primary-button'),btn('Import settings',()=>{importMode='settings';$('importInput').click();}));actionRow(data,btn('Reset everything',resetEverything,'danger-button'));const diag=group(x,'Diagnostics','Useful when connecting App Inventor.');diag.append(el('pre','diagnostics',`Bridge: ${appMode()?'App Inventor':'Demo'}\nStorage: ${storageOK?'Available':'Unavailable'}\nState version: ${C.VERSION}\nTabs: ${state.tabs.length}`));}
async function saveProfile(){const name=await ask('Save customization profile','This saves theme, effects, layout, and browser preferences.',{value:'My setup'});if(!name)return;state.profiles.push({id:C.uid('profile'),name,prefs:C.clone(p)});save();makeSettings();showSettings('advanced');}
async function resetEverything(){const ok=await ask('Reset blobby.vip?','This removes saved themes, layouts, profiles, shortcuts, history, and preferences from this browser.',{accept:'Reset',input:false});if(!ok)return;state=C.defaults();p=state.prefs;save();makeSettings();apply();showSettings('advanced');}
function showSettings(id){activeSettings=id;for(const [key] of categories){const pn=$('settings-'+key),nb=document.querySelector(`.settings-nav-button[data-category="${key}"]`);if(pn)pn.hidden=key!==id;if(nb)nb.setAttribute('aria-current',String(key===id));}syncSettingsSearch();}
function openSettings(id=activeSettings){expandUI('settings');makeSettings();showSettings(id);$('settingsDialog').showModal();setTimeout(()=>$('settingsSearch').focus(),20);}
$('settingsButton').onclick=()=>openSettings();
$('settingsDialog').addEventListener('close',()=>restoreUI('settings')); 
$('settingsSearch').addEventListener('input',syncSettingsSearch);
function syncSettingsSearch(){const q=$('settingsSearch').value.trim().toLowerCase();if(!q){for(const [key] of categories){const pn=$('settings-'+key),nb=document.querySelector(`.settings-nav-button[data-category="${key}"]`);if(pn)pn.hidden=key!==activeSettings;if(nb)nb.hidden=false;}document.querySelectorAll('.search-hidden').forEach(n=>n.classList.remove('search-hidden'));return;}for(const [key] of categories){const pn=$('settings-'+key),nb=document.querySelector(`.settings-nav-button[data-category="${key}"]`);if(!pn)continue;const hit=pn.textContent.toLowerCase().includes(q);pn.hidden=!hit;if(nb)nb.hidden=!hit;}document.querySelectorAll('.setting-row,.theme-card,.saved-item').forEach(node=>{node.classList.toggle('search-hidden',!node.textContent.toLowerCase().includes(q)&&!(node.dataset.settingSearch||'').includes(q));});}
function syncSettings(){const hint=C.engines[p.engine]?.name||'Custom';$('searchEngineHint').textContent=`Search with ${hint}`;if(!$('settingsDialog').open)return;}
function changed(saveNow=true){state.prefs=p;if(saveNow)save();apply();}

function startLayoutEdit(){if(p.layoutLocked){say('Unlock the layout in Settings → Layout before editing.');return;}if($('settingsDialog').open)$('settingsDialog').close();expandUI('layout');layoutSnapshot=C.clone(p.layoutOrder);pendingOrder=C.clone(p.layoutOrder);L.enableEditor(shell,true);$('layoutToolbar').hidden=false;shell.dataset.layoutEditing='true';say('Layout editing enabled. Drag blocks using their handles.');}
L.bindDrag(shell,{onOrder:order=>{pendingOrder=order;}});$('layoutEditButton').onclick=startLayoutEdit;
$('saveLayoutOrderButton').onclick=()=>{if(pendingOrder)p.layoutOrder=C.clone(pendingOrder);L.enableEditor(shell,false);$('layoutToolbar').hidden=true;shell.dataset.layoutEditing='false';save();apply();restoreUI('layout');say('Layout saved.');};
$('cancelLayoutEditButton').onclick=()=>{if(layoutSnapshot)p.layoutOrder=C.clone(layoutSnapshot);L.enableEditor(shell,false);$('layoutToolbar').hidden=true;shell.dataset.layoutEditing='false';apply();restoreUI('layout');say('Layout changes canceled.');};
$('lockLayoutButton').onclick=()=>{p.layoutLocked=!p.layoutLocked;$('lockLayoutButton').textContent=p.layoutLocked?'Unlock':'Lock';save();say(p.layoutLocked?'Layout locked.':'Layout unlocked.');};

$('backgroundUpload').addEventListener('change',()=>{const file=$('backgroundUpload').files[0];if(!file)return;if(file.size>2_000_000){say('Background image must be under 2 MB so local storage does not overflow.');return;}const reader=new FileReader();reader.onload=()=>{p.backgroundImage=reader.result;p.backgroundMode='image';changed();};reader.readAsDataURL(file);});
$('importInput').addEventListener('change',async()=>{const file=$('importInput').files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(importMode==='theme'){if(data.type!=='blobby-theme'||!T.validTheme(data.colors))throw Error('Not a blobby.vip theme file');const t={id:C.uid('theme'),name:String(data.name||'Imported theme').slice(0,48),colors:data.colors};state.customThemes.push(t);p.theme=t.id;changed();makeSettings();showSettings('themes');}
 else{if(data.type!=='blobby-settings'||!data.state)throw Error('Not a blobby.vip settings file');state=C.migrate((key,fallback)=>key===C.STORAGE_KEY?data.state:fallback);p=state.prefs;save();makeSettings();apply();showSettings('advanced');}say('Import complete.');}catch(err){say('Import failed: '+err.message);}finally{$('importInput').value='';}});

function updateClock(){const now=new Date();$('clockTime').textContent=now.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});$('clockDate').textContent=now.toLocaleDateString([],{weekday:'long',month:'long',day:'numeric'});}updateClock();setInterval(updateClock,30000);
function focusHomeSearch(){if(p.autofocus&&matchMedia('(pointer:fine)').matches)setTimeout(()=>$('homeSearchInput').focus(),20);}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('settingsDialog').open)$('settingsDialog').close();if(e.key==='/'&&!document.querySelector('dialog[open]')&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();$('homeSearchInput').focus();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='l'){e.preventDefault();$('addressBar').focus();$('addressBar').select();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='t'){e.preventDefault();newTab();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='w'){e.preventDefault();closeTab(state.activeTab);}});
document.addEventListener('visibilitychange',()=>effects.refresh());
makeSettings();apply();focusHomeSearch();
})();
