(function(root){
'use strict';
class EffectsEngine{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.items={};this.frame=0;this.last=0;this.cfg=null;this.resize=this.resize.bind(this);addEventListener('resize',this.resize);document.addEventListener('visibilitychange',()=>this.refresh());}
 configure(prefs,theme){this.cfg={prefs,theme};const r=document.documentElement,e=prefs.effects||{};r.dataset.aurora=String(!!e.aurora&&!prefs.performance&&prefs.effectsMaster);r.dataset.fog=String(!!e.fog&&!prefs.performance&&prefs.effectsMaster);r.dataset.waves=String(!!e.waves&&!prefs.performance&&prefs.effectsMaster);r.dataset.rgbGlow=String(!!e.rgbGlow&&!prefs.performance&&prefs.effectsMaster);r.dataset.rainGlass=String(!!prefs.rainGlass&&!!e.rain&&!prefs.performance&&prefs.effectsMaster);this.rebuild();this.refresh();}
 active(){if(!this.cfg)return false;const p=this.cfg.prefs;if(document.hidden||p.performance||p.reducedMotion||!p.effectsMaster)return false;const e=p.effects||{};return ['snow','rain','stars','particles','fireflies','orbs','matrix','bubbles','shooting','dust'].some(k=>e[k]);}
 resize(){const d=Math.min(devicePixelRatio||1,1.5),w=innerWidth,h=innerHeight;this.canvas.width=Math.max(1,Math.floor(w*d));this.canvas.height=Math.max(1,Math.floor(h*d));this.canvas.style.width=w+'px';this.canvas.style.height=h+'px';this.ctx.setTransform(d,0,0,d,0,0);this.w=w;this.h=h;this.rebuild();}
 count(base){const p=this.cfg.prefs;return Math.max(4,Math.round(base*(p.effectDensity/50)));}
 rebuild(){if(!this.cfg)return;this.resizeCanvasOnly();const p=this.cfg.prefs,e=p.effects||{},w=this.w||innerWidth,h=this.h||innerHeight,size=p.effectSize||1;this.items={};
  if(e.snow)this.items.snow=Array.from({length:this.count(44)},()=>({x:Math.random()*w,y:Math.random()*h,r:(1+Math.random()*2.4)*size,v:16+Math.random()*30,drift:-8+Math.random()*16}));
  if(e.rain)this.items.rain=Array.from({length:this.count(75)},()=>({x:Math.random()*w,y:Math.random()*h,l:(8+Math.random()*18)*size,v:420+Math.random()*420}));
  if(e.stars)this.items.stars=Array.from({length:this.count(65)},()=>({x:Math.random()*w,y:Math.random()*h,r:(.5+Math.random()*1.3)*size,a:.25+Math.random()*.65,t:Math.random()*6}));
  if(e.particles)this.items.particles=Array.from({length:this.count(28)},()=>({x:Math.random()*w,y:Math.random()*h,r:(1+Math.random()*2)*size,vx:-8+Math.random()*16,vy:-8+Math.random()*16}));
  if(e.fireflies)this.items.fireflies=Array.from({length:this.count(18)},()=>({x:Math.random()*w,y:Math.random()*h,r:(1.5+Math.random()*2)*size,vx:-10+Math.random()*20,vy:-8+Math.random()*16,t:Math.random()*8}));
  if(e.orbs)this.items.orbs=Array.from({length:this.count(10)},()=>({x:Math.random()*w,y:Math.random()*h,r:(20+Math.random()*55)*size,vx:-4+Math.random()*8,vy:-3+Math.random()*6}));
  if(e.matrix)this.items.matrix=Array.from({length:Math.max(8,Math.round(w/26))},(_,i)=>({x:i*26+Math.random()*16,y:Math.random()*h,v:70+Math.random()*130,char:String.fromCharCode(0x30A0+Math.floor(Math.random()*80))}));
  if(e.bubbles)this.items.bubbles=Array.from({length:this.count(18)},()=>({x:Math.random()*w,y:Math.random()*h,r:(3+Math.random()*9)*size,v:12+Math.random()*28,drift:-8+Math.random()*16}));
  if(e.dust)this.items.dust=Array.from({length:this.count(34)},()=>({x:Math.random()*w,y:Math.random()*h,r:(.5+Math.random()*1.4)*size,vx:-3+Math.random()*6,vy:-2+Math.random()*4}));
  if(e.shooting)this.items.shooting=[{x:-100,y:h*.2,v:0,next:performance.now()+1500+Math.random()*3500}];
 }
 resizeCanvasOnly(){const d=Math.min(devicePixelRatio||1,1.5),w=innerWidth,h=innerHeight;if(this.w===w&&this.h===h&&this.canvas.width)return;this.canvas.width=Math.max(1,Math.floor(w*d));this.canvas.height=Math.max(1,Math.floor(h*d));this.canvas.style.width=w+'px';this.canvas.style.height=h+'px';this.ctx.setTransform(d,0,0,d,0,0);this.w=w;this.h=h;}
 refresh(){if(this.active()){this.canvas.hidden=false;if(!this.frame){this.last=0;this.frame=requestAnimationFrame(t=>this.tick(t));}}else{if(this.frame)cancelAnimationFrame(this.frame);this.frame=0;this.canvas.hidden=true;this.ctx.clearRect(0,0,this.w||0,this.h||0);}}
 tick(t){this.frame=0;if(!this.active())return;const p=this.cfg.prefs,theme=this.cfg.theme||{},dt=this.last?Math.min((t-this.last)/1000,.05):0;this.last=t;const c=this.ctx,w=this.w,h=this.h,spd=p.effectSpeed||1,alpha=p.effectOpacity||.55;c.clearRect(0,0,w,h);
  if(this.items.orbs){for(const o of this.items.orbs){o.x+=o.vx*spd*dt;o.y+=o.vy*spd*dt;if(o.x<-o.r)o.x=w+o.r;if(o.x>w+o.r)o.x=-o.r;if(o.y<-o.r)o.y=h+o.r;if(o.y>h+o.r)o.y=-o.r;const g=c.createRadialGradient(o.x,o.y,0,o.x,o.y,o.r);g.addColorStop(0,(theme.accent||'#8da2ff')+'55');g.addColorStop(1,(theme.accent2||'#b28cff')+'00');c.fillStyle=g;c.globalAlpha=alpha*.75;c.beginPath();c.arc(o.x,o.y,o.r,0,Math.PI*2);c.fill();}}
  if(this.items.stars){c.fillStyle='#ffffff';for(const s of this.items.stars){s.t+=dt*spd;c.globalAlpha=alpha*(s.a*(.65+.35*Math.sin(s.t)));c.beginPath();c.arc(s.x,s.y,s.r,0,Math.PI*2);c.fill();}}
  if(this.items.snow){c.fillStyle='#ffffff';c.globalAlpha=alpha;for(const s of this.items.snow){s.y+=s.v*spd*dt;s.x+=s.drift*spd*dt;if(s.y>h+5){s.y=-5;s.x=Math.random()*w}if(s.x<-5)s.x=w+5;if(s.x>w+5)s.x=-5;c.beginPath();c.arc(s.x,s.y,s.r,0,Math.PI*2);c.fill();}}
  if(this.items.rain){c.strokeStyle=theme.accent2||'#74b7ff';c.lineWidth=1.15;c.globalAlpha=alpha*.75;c.beginPath();for(const r of this.items.rain){r.y+=r.v*spd*dt;r.x-=r.v*.08*spd*dt;if(r.y>h+30||r.x<-30){r.y=-30-Math.random()*h*.2;r.x=Math.random()*(w+100)}c.moveTo(r.x,r.y);c.lineTo(r.x-r.l*.25,r.y+r.l);}c.stroke();if(p.rainLightning&&Math.random()<.0015*spd)document.documentElement.animate([{filter:'brightness(1)'},{filter:'brightness(1.55)'},{filter:'brightness(1)'}],{duration:180});}
  if(this.items.particles){c.fillStyle=theme.accent||'#8da2ff';c.globalAlpha=alpha*.55;for(const q of this.items.particles){q.x+=q.vx*spd*dt;q.y+=q.vy*spd*dt;if(q.x<0||q.x>w)q.vx*=-1;if(q.y<0||q.y>h)q.vy*=-1;c.beginPath();c.arc(q.x,q.y,q.r,0,Math.PI*2);c.fill();}}
  if(this.items.fireflies){for(const f of this.items.fireflies){f.t+=dt*spd;f.x+=f.vx*spd*dt;f.y+=f.vy*spd*dt;if(f.x<0||f.x>w)f.vx*=-1;if(f.y<0||f.y>h)f.vy*=-1;c.fillStyle='#d6ff73';c.globalAlpha=alpha*(.35+.65*(.5+.5*Math.sin(f.t*2)));c.shadowBlur=12;c.shadowColor='#d6ff73';c.beginPath();c.arc(f.x,f.y,f.r,0,Math.PI*2);c.fill();c.shadowBlur=0;}}
  if(this.items.matrix){c.font='14px monospace';c.fillStyle='#63ff7c';for(const m of this.items.matrix){m.y+=m.v*spd*dt;if(m.y>h+20)m.y=-20;c.globalAlpha=alpha*.65;c.fillText(m.char,m.x,m.y);if(Math.random()<.035)m.char=String.fromCharCode(0x30A0+Math.floor(Math.random()*80));}}
  if(this.items.bubbles){c.strokeStyle=theme.accent2||'#7cdcff';c.lineWidth=1;c.globalAlpha=alpha*.65;for(const b of this.items.bubbles){b.y-=b.v*spd*dt;b.x+=b.drift*spd*dt;if(b.y<-15){b.y=h+15;b.x=Math.random()*w}c.beginPath();c.arc(b.x,b.y,b.r,0,Math.PI*2);c.stroke();}}
  if(this.items.dust){c.fillStyle='#ffffff';c.globalAlpha=alpha*.25;for(const d of this.items.dust){d.x+=d.vx*spd*dt;d.y+=d.vy*spd*dt;if(d.x<0)d.x=w;if(d.x>w)d.x=0;if(d.y<0)d.y=h;if(d.y>h)d.y=0;c.beginPath();c.arc(d.x,d.y,d.r,0,Math.PI*2);c.fill();}}
  if(this.items.shooting){const s=this.items.shooting[0];if(t>s.next){s.v+=1100*dt;s.x+=s.v*dt;s.y+=s.v*.28*dt;c.strokeStyle='#fff';c.lineWidth=1.4;c.globalAlpha=alpha;c.beginPath();c.moveTo(s.x,s.y);c.lineTo(s.x-90,s.y-26);c.stroke();if(s.x>w+150){s.x=-120;s.y=40+Math.random()*h*.45;s.v=0;s.next=t+2000+Math.random()*6000;}}}
  c.globalAlpha=1;this.frame=requestAnimationFrame(x=>this.tick(x));}
 destroy(){if(this.frame)cancelAnimationFrame(this.frame);removeEventListener('resize',this.resize);}
}
root.BlobbyEffects={EffectsEngine};
})(window);
