(function(root){
'use strict';
const C=root.BlobbyCore,COLS=12,ROWS=12;
function pos(el){return {col:+el.dataset.gridCol||1,row:+el.dataset.gridRow||1,w:+el.dataset.gridW||1,h:+el.dataset.gridH||1};}
function setPos(el,p,commit=true){el.style.gridColumn=`${p.col} / span ${p.w}`;el.style.gridRow=`${p.row} / span ${p.h}`;if(commit){el.dataset.gridCol=p.col;el.dataset.gridRow=p.row;el.dataset.gridW=p.w;el.dataset.gridH=p.h;}}
function overlaps(a,b){return a.col<b.col+b.w&&a.col+a.w>b.col&&a.row<b.row+b.h&&a.row+a.h>b.row;}
function occupied(container,skip){return [...container.querySelectorAll('[data-layout-item]')].filter(el=>el!==skip&&!el.hidden).map(el=>({el,...pos(el)}));}
function canPlace(container,item,p){if(p.col<1||p.row<1||p.col+p.w-1>COLS||p.row+p.h-1>ROWS)return false;return !occupied(container,item).some(o=>overlaps(p,o));}
function firstFree(container,item,p){if(canPlace(container,item,p))return p;for(let r=1;r<=ROWS-p.h+1;r++)for(let c=1;c<=COLS-p.w+1;c++){const q={...p,col:c,row:r};if(canPlace(container,item,q))return q;}return p;}
function apply(prefs,container=document.getElementById('appShell')){if(!container)return;const hidden=new Set(prefs.layoutHidden||[]);container.dataset.layoutPreset=prefs.layoutPreset||'classic';container.querySelectorAll('[data-layout-item]').forEach(el=>{const id=el.dataset.layoutItem;let hide=hidden.has(id);if(id==='clock'&&!prefs.showClock)hide=true;if(id==='shortcuts'&&!prefs.showShortcuts)hide=true;if(id==='recent'&&!prefs.showRecent)hide=true;if(id==='preview'&&!prefs.showPreview)hide=true;el.hidden=hide;});
 const grid=C.sanitizeGrid(prefs.layoutGrid||C.defaultLayoutGrid);for(const id of C.layoutItemIds){const el=container.querySelector(`[data-layout-item="${id}"]`);if(el)setPos(el,grid[id],true);}const placed=[];for(const id of C.layoutItemIds){const el=container.querySelector(`[data-layout-item="${id}"]`);if(!el||el.hidden)continue;let q={...grid[id]};const free=x=>x.col>=1&&x.row>=1&&x.col+x.w-1<=COLS&&x.row+x.h-1<=ROWS&&!placed.some(o=>overlaps(x,o));if(!free(q)){outer:for(let r=1;r<=ROWS-q.h+1;r++)for(let c=1;c<=COLS-q.w+1;c++){const test={...q,col:c,row:r};if(free(test)){q=test;break outer;}}}grid[id]=q;setPos(el,q,true);placed.push(q);}prefs.layoutGrid=grid;}
function usePreset(prefs,id){const preset=C.layoutPresets[id]||C.layoutPresets.classic;prefs.layoutPreset=id;prefs.layoutGrid=C.clone(preset.grid);prefs.layoutHidden=C.clone(preset.hidden);return prefs;}
function ensureGuide(container){let guide=container.querySelector('#layoutGridGuide');if(!guide)return null;if(!guide.childElementCount){for(let r=1;r<=ROWS;r++)for(let c=1;c<=COLS;c++){const cell=document.createElement('i');cell.dataset.col=c;cell.dataset.row=r;guide.append(cell);}}return guide;}
function paintGuide(container,p,valid){const g=ensureGuide(container);if(!g)return;g.querySelectorAll('i').forEach(x=>x.className='');if(!p)return;for(let r=p.row;r<p.row+p.h;r++)for(let c=p.col;c<p.col+p.w;c++){const cell=g.querySelector(`i[data-col="${c}"][data-row="${r}"]`);if(cell)cell.className=valid?'target-valid':'target-blocked';}}
function clearGuide(container){const g=ensureGuide(container);if(g)g.querySelectorAll('i').forEach(x=>x.className='');}
function enableEditor(container,on){container.dataset.layoutEditing=String(!!on);const guide=ensureGuide(container);if(guide)guide.hidden=!on;container.querySelectorAll('[data-layout-item] .drag-handle').forEach(h=>{h.tabIndex=on?0:-1;h.setAttribute('aria-hidden',String(!on));});clearGuide(container);}
function snapshot(container){const out={};container.querySelectorAll('[data-layout-item]').forEach(el=>out[el.dataset.layoutItem]=pos(el));return out;}
function pointerCell(container,e,size){const rect=container.getBoundingClientRect(),cs=getComputedStyle(container),gap=parseFloat(cs.columnGap)||10,rowH=parseFloat(cs.getPropertyValue('--grid-row'))||72,colW=(rect.width-gap*(COLS-1))/COLS;const x=Math.max(0,e.clientX-rect.left),y=Math.max(0,e.clientY-rect.top);let col=Math.floor(x/(colW+gap))+1,row=Math.floor(y/(rowH+gap))+1;col=Math.max(1,Math.min(COLS-size.w+1,col));row=Math.max(1,Math.min(ROWS-size.h+1,row));return {...size,col,row};}
function bindGrid(container,{onGrid,onCollision}={}){let drag=null;
 container.addEventListener('pointerdown',e=>{if(container.dataset.layoutEditing!=='true')return;const handle=e.target.closest&&e.target.closest('.drag-handle'),item=handle&&handle.closest('[data-layout-item]');if(!item||item.hidden)return;e.preventDefault();const origin=pos(item);drag={item,origin,last:origin,handle,pointerId:e.pointerId};item.classList.add('dragging');try{handle.setPointerCapture(e.pointerId);}catch{}paintGuide(container,origin,true);});
 container.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointerId)return;e.preventDefault();const candidate=pointerCell(container,e,drag.origin),valid=canPlace(container,drag.item,candidate);paintGuide(container,candidate,valid);drag.item.classList.toggle('collision',!valid);if(valid){drag.last=candidate;setPos(drag.item,candidate,false);}});
 function finish(e,cancel=false){if(!drag)return;if(e&&e.pointerId!==undefined&&e.pointerId!==drag.pointerId)return;const d=drag;drag=null;d.item.classList.remove('dragging','collision');const final=cancel?d.origin:d.last;setPos(d.item,final,true);clearGuide(container);if(!cancel&&onGrid)onGrid(snapshot(container));}
 container.addEventListener('pointerup',e=>finish(e,false));container.addEventListener('pointercancel',e=>finish(e,true));
 container.addEventListener('keydown',e=>{if(container.dataset.layoutEditing!=='true'||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;const handle=e.target.closest&&e.target.closest('.drag-handle'),item=handle&&handle.closest('[data-layout-item]');if(!item)return;e.preventDefault();const p=pos(item),next={...p};if(e.key==='ArrowLeft')next.col--;if(e.key==='ArrowRight')next.col++;if(e.key==='ArrowUp')next.row--;if(e.key==='ArrowDown')next.row++;if(canPlace(container,item,next)){setPos(item,next,true);paintGuide(container,next,true);if(onGrid)onGrid(snapshot(container));}else{paintGuide(container,next,false);item.classList.add('collision');setTimeout(()=>item.classList.remove('collision'),180);if(onCollision)onCollision(item.dataset.layoutItem);}});
}
root.BlobbyLayout={apply,usePreset,enableEditor,bindGrid,snapshot,canPlace};
})(window);
