(function(root){
'use strict';
const C=root.BlobbyCore;
function apply(prefs,container=document.getElementById('appShell')){if(!container)return;const order=prefs.layoutOrder||C.defaultLayoutOrder;const hidden=new Set(prefs.layoutHidden||[]);order.forEach((id,index)=>{const el=container.querySelector(`[data-layout-item="${id}"]`);if(el)el.style.order=String(index)});container.dataset.layoutPreset=prefs.layoutPreset||'classic';container.querySelectorAll('[data-layout-item]').forEach(el=>{const id=el.dataset.layoutItem;let hide=hidden.has(id);if(id==='clock'&&!prefs.showClock)hide=true;if(id==='shortcuts'&&!prefs.showShortcuts)hide=true;if(id==='recent'&&!prefs.showRecent)hide=true;if(id==='preview'&&!prefs.showPreview)hide=true;el.hidden=hide;});}
function usePreset(prefs,id){const preset=C.layoutPresets[id]||C.layoutPresets.classic;prefs.layoutPreset=id;prefs.layoutOrder=C.clone(preset.order);prefs.layoutHidden=C.clone(preset.hidden);return prefs;}
function enableEditor(container,on){container.dataset.layoutEditing=String(!!on);container.querySelectorAll('[data-layout-item]').forEach(el=>{el.draggable=!!on;});}
function bindDrag(container,{onOrder}={}){let from=null;container.addEventListener('dragstart',e=>{const item=e.target.closest&&e.target.closest('[data-layout-item]');if(!item||container.dataset.layoutEditing!=='true'){e.preventDefault();return;}from=item;item.classList.add('dragging');if(e.dataTransfer){e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',item.dataset.layoutItem);}});
 container.addEventListener('dragend',()=>{container.querySelectorAll('[data-layout-item]').forEach(x=>x.classList.remove('dragging','drag-over'));from=null;});
 container.addEventListener('dragover',e=>{if(!from)return;const to=e.target.closest&&e.target.closest('[data-layout-item]');if(!to||to===from)return;e.preventDefault();container.querySelectorAll('[data-layout-item]').forEach(x=>x.classList.remove('drag-over'));to.classList.add('drag-over');});
 container.addEventListener('drop',e=>{if(!from)return;const to=e.target.closest&&e.target.closest('[data-layout-item]');if(!to||to===from)return;e.preventDefault();const items=[...container.querySelectorAll('[data-layout-item]')].sort((a,b)=>(+a.style.order||0)-(+b.style.order||0));const order=items.map(x=>x.dataset.layoutItem);const fi=order.indexOf(from.dataset.layoutItem),ti=order.indexOf(to.dataset.layoutItem);order.splice(ti,0,order.splice(fi,1)[0]);order.forEach((id,i)=>{const el=container.querySelector(`[data-layout-item="${id}"]`);if(el)el.style.order=String(i);});to.classList.remove('drag-over');if(onOrder)onOrder(order);});}
root.BlobbyLayout={apply,usePreset,enableEditor,bindDrag};
})(window);
